{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $can_view=and($child_survey.enabled,$child_survey.published,$child_survey.valid)}
{if $can_view}
<a href={concat("survey/view/",$child_survey.id)|ezurl} class="nodeicon">
{/if}
{$Nodes.item.class_identifier|class_icon( small,'')}
{if $can_view}
</a>
{/if}
&nbsp;
{if $can_view}
<a href={concat("survey/view/",$child_survey.id)|ezurl}>
{/if}
{$Nodes.item.name|wash}
{if $can_view}
</a>
{/if}
